CREATE TABLE CONTACT (
  ID          SERIAL,
  FIRST_NAME  VARCHAR(60),
  LAST_NAME   VARCHAR(60),
  BIRTH_DATE  DATE,
  DESCRIPTION VARCHAR(2000),
  PHOTO       BYTEA,
  VERSION     INT NOT NULL DEFAULT 0,
  UNIQUE (FIRST_NAME, LAST_NAME),
  PRIMARY KEY (ID)
);